language: ruby
rvm:
 - "2.2.1"
services:
 - postgresql
before_script:
 - cp config/database.yml.travis config/database.yml
 - psql -c 'create database travis_ci_test;' -U postgres
 # Attempt to run db migrations and resolve error
 - bundle exec rake db:migrate
 - bundle exec rake secrets:generate
 # Settings to run xvfb for headless browser testing
 # Further info at https://docs.travis-ci.com/user/gui-and-headless-browsers/
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
addons:
    code_climate:
        repo_token: 5baf7aa67cacb78fe966d07be7df2a36febb481a521783ea86f15d41c8c4b8a8
